1. Select Name, Title, Phone, Email from Contact;
2. Select Name, Title, Phone, Email from Contact where title ='VP Technology';
3. Select Name, Department, Title, Phone, Email from Contact where title ='VP Technology';
4. Select Name, Title, Phone, Email from Contact where title ='VP Technology' and department ='Finance';
6. Select Name, Title, Phone, Email from Contact where title ='%VP%' and department ='Finance';
7. Select Name, Title, Phone, Email from Contact where title ='%VP%' and department ='Finance' order by Name Desc;
8. Select Name, Title, Phone, Email from Contact where title ='%VP%' and department ='Finance' order by Name Desc limit 3;
